AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    BinaryMediaTypes:
      - application~1pdf

Resources:
  # Define an API GateWay
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: GatewayAuthorization
    BinaryMediaTypes:
      - application~1pdf
    # BinaryMediaTypes:
    #   - '*~1*'
    # DefinitionBody:
    #   x-amazon-apigateway-binary-media-types:
    #     - '*/*'

  # Define the consumer Lambda function and EventBridge rule
  PdfFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 15
      MemorySize: 3008

      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:764866452798:layer:chrome-aws-lambda:22'
      # Environment:
      #   Variables:
      #     EXAMPLE_ENV: 'CHANGE_THIS'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /pdf
            Method: post
            Auth:
              ApiKeyRequired: true
            RestApiId:
              Ref: ApiGatewayApi
Outputs:
  ApiGatewayApi:
    Description: "The URL is:"
    Value:
      Fn::Sub: https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  ApiKey:
    Description: "You can find your API Key in the AWS console: (Put in the request HEADER as 'x-api-key')"
    Value: !Sub "https://console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/api-keys/"
